version: "3.8"

networks:
  mini-labelon-network:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"

    networks:
      - mini-labelon-network
